### ISSUE TITLE
[Bug] Latest SfRotator raises ArgumentOutOfRangeException on UWP

### ISSUE THREAD

**Issue by SunshineSpring666** [syncfusion/xamarin-demos#42]
Hi team,
Latest SfRotator (v18.4.0.49) raises exception on UWP:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
   at System.Runtime.InteropServices.WindowsRuntime.VectorToListAdapter.GetAt[T](IVector`1 _this, UInt32 index)
   at Syncfusion.UI.Xaml.Rotator.SliderItemsPanel.MoveSelectedIndex(Int32 index, Boolean isupdate, Boolean isItemChanged)
   at Syncfusion.UI.Xaml.Rotator.SfRotator.OnItemsChanged(Object e)
   at Windows.UI.Xaml.Controls.ItemsControl.put_ItemsSource(Object value)

while previous versions ( <= v18.4.0.48) runs normally.

**Comment by SunshineSpring666** [comment]
Update:
Issue exists in update v18.4.0.54
Thanks

**Comment by Suganyasheela** [comment]
Hi SunshineSpring666,

We have analyzed the reported issue. We have tried to replicate the reported issue at our end, we are afraid that we are not able to reproduce the issue at our end. But we have fixed the issue based on the stack trace provided. We suspect the issue has been fixed. Please find the assembly for this below.

Custom Assemblies: https://www.syncfusion.com/downloads/support/directtrac/general/ze/RotatorItemAssembly78932086

Assembly version : 19.1.0.54

Please refer the  below link for how to apply custom assemblies.
https://www.syncfusion.com/kb/8279/how-to-apply-the-custom-assemblies-when-configured-the-project-with-syncfusion-nuget 

Could you please check this fix with your application and let us know, whether the issue is resolved or not.

Regards,
Suganya Sethuraman.

**Comment by SunshineSpring666** [comment]
Update:
System.ArgumentOutOfRangeException still got raised **occasionally** using the Custom Assemblies(v19.1.0.54)

**Comment by Suganyasheela** [comment]
Hi SunshineSpring666,

Sorry for the inconvenience.

We have not included this fix since some test cases are pending. This fix will be included in the next weekly NuGet release, which is scheduled for April 13, 2021. please check the next weekly release and let us know the reported issue is resolved from your side or not.

Regards,
Suganya Sethuraman

**Comment by SunshineSpring666** [comment]
Hi Team,
Thanks. I'll provide feedback as soon as the issue disappears on my side.

**Comment by Suganyasheela** [comment]
Hi SunshineSpring666,

Thanks for the patience.

We have included the fix in our latest Weekly NuGet release v19.1.0.56 which is available for download (https://www.nuget.org). We thank you for your support and appreciate your patience in waiting for this update. Please get in touch with us if you would require any further assistance.

Regards,
Suganya Sethuraman.

**Comment by SunshineSpring666** [comment]
Hi Team,
I've updated to the latest nuget package, but unfortunately, the issue **still exists occasionally** with exact same ItemsSource data.
Code Snippet:

<rtt:SfRotator ItemsSource="{Binding Announcements}" HeightRequest="40" NavigationDelay="5000" NavigationDirection="Vertical" EnableAutoPlay="{Binding EnableAutoPlay}" 
                                   BackgroundColor="Transparent"  SelectedDotColor="Transparent" UnselectedDotColor="Transparent" DotsBorderColor="Transparent">
            <rtt:SfRotator.ItemTemplate>
                <DataTemplate x:DataType="md:Announcement">
                    <Button Text="{Binding Message}" Clicked="CurrentAnnouncementTapped" TextColor="{Binding TimeModified, StringFormat='{0:yy-MM-dd HH:mm}', Converter={StaticResource RecentAsRed}}" HorizontalOptions="FillAndExpand" BackgroundColor="Transparent"/>
                </DataTemplate>
            </rtt:SfRotator.ItemTemplate>
        </rtt:SfRotator>

I also tried to enable auto play only when the data in observable collection is fetched and loaded in the Announcements, which doesn't help.
Thanks a lot.

Regards,
Sunshine

**Comment by Suganyasheela** [comment]
Hi SunshineSpring666,

As per the initial update we could not reproduce the issue from our side, and we have applied the fix based on the stack trace and that fix will be included in previous weekly NuGet release. Now we have added more possible condition based on the same stack trace, please check the following updated fix and let us know the reported issue is resolved from your side.

Custom assemblies: https://www.syncfusion.com/downloads/support/directtrac/general/ze/RotatorItemAssembly-879598141

Please refer the below link for how to apply custom assemblies.
https://www.syncfusion.com/kb/8279/how-to-apply-the-custom-assemblies-when-configured-the-project-with-syncfusion-nuget

If you still face the same problem means, please revert us the simple sample which replicate the reported issue which will be more helpful to proceed further and fix this issue from your side.

Regards,
Suganya Sethuraman.

**Comment by SunshineSpring666** [comment]
Update:
1) Issue disappears with the above custom assemblies 
    (https://www.syncfusion.com/downloads/support/directtrac/general/ze/RotatorItemAssembly-879598141).
2) Issue exists with latest NuGet release v19.1.0.57.

Thanks a lot.

Regards,
Sunshine

**Comment by SunshineSpring666** [comment]
Update:
   I failed to make the issue appear in demo project, weird. But when switching from the page in our project it appear occasionally. I'll temporarily comment out related code and provide feedback once things goes normal in future.
   Thank you so much for all these patient replies.

**Comment by Suganyasheela** [comment]
Hi SunshineSpring666,

Thanks for the update.

We would like to discuss more about your issue, so please share your details to support@syncfusion.com mail id, which will be helpful for us to proceed further.

Regards,
Suganya Sethuraman.

**Comment by SunshineSpring666** [comment]
Thanks. OK, I sent the email.

**Comment by SunshineSpring666** [comment]
Update:
    The issue exists when a SfRotator's ItemsSource ObservableCollection grows in size.
    For example, if the bound ItemsSource is declared as an initial empty ObservableCollection in a page like this:
        public ObservableCollection<Announcement> Announcements { get; set; } = new ObservableCollection<Announcement>();
    Then in the overridden OnAppearing method, if the data is got from server with a count larger than its initial value, and reassigned to Announcements, the ArgumentOutOfRangeException is raised.
    Same situation exists in SfStepProgressBar when the bound ItemsSource grows in count as the bound data get reassigned to its latest data as the code runs.
    Sorry for my poor English. Thanks a lot.

**Comment by SunshineSpring666** [comment]
For SfRotator and SfStepProgressBar,
if the bound observable collection is reassigned with a new collection (larger size), issue happens;
if data is added in the bound observable collection, issue doesn't happen. 
That's it. Thanks.
Best Regards,
Sunshine
